from typing import Any, Sequence

# --- Constants ---

GL_VERTEX_SHADER: int
GL_FRAGMENT_SHADER: int

GL_COMPILE_STATUS: int
GL_LINK_STATUS: int

GL_TEXTURE_2D: int
GL_UNPACK_ALIGNMENT: int
GL_TEXTURE_MIN_FILTER: int
GL_TEXTURE_MAG_FILTER: int
GL_TEXTURE_WRAP_S: int
GL_TEXTURE_WRAP_T: int
GL_CLAMP_TO_EDGE: int
GL_LINEAR: int
GL_NEAREST: int
GL_LINEAR_MIPMAP_LINEAR: int

GL_RGBA: int
GL_UNSIGNED_BYTE: int

GL_COLOR_BUFFER_BIT: int
GL_DEPTH_TEST: int

GL_ARRAY_BUFFER: int
GL_DYNAMIC_DRAW: int

GL_FLOAT: int
GL_FALSE: int

GL_TRIANGLES: int

GL_TEXTURE0: int

GL_BLEND: int
GL_ONE: int
GL_ONE_MINUS_SRC_ALPHA: int

# For version / GLSL queries
GL_VERSION: int
GL_SHADING_LANGUAGE_VERSION: int

# --- Shader / program functions ---

def glCreateShader(shaderType: int) -> int: ...
def glShaderSource(shader: int, source: str | bytes) -> None: ...
def glCompileShader(shader: int) -> None: ...
def glGetShaderiv(shader: int, pname: int) -> int: ...
def glGetShaderInfoLog(shader: int) -> bytes: ...
def glCreateProgram() -> int: ...
def glAttachShader(program: int, shader: int) -> None: ...
def glLinkProgram(program: int) -> None: ...
def glGetProgramiv(program: int, pname: int) -> int: ...
def glGetProgramInfoLog(program: int) -> bytes: ...
def glDetachShader(program: int, shader: int) -> None: ...
def glDeleteShader(shader: int) -> None: ...
def glGetAttribLocation(program: int, name: str) -> int: ...
def glGetUniformLocation(program: int, name: str) -> int: ...
def glUseProgram(program: int) -> None: ...
def glDeleteProgram(program: int) -> None: ...

# --- Buffer / VAO functions ---

def glGenBuffers(n: int) -> int: ...
def glBindBuffer(target: int, buffer: int) -> None: ...
def glBufferData(target: int, size: int, data: Any, usage: int) -> None: ...
def glDeleteBuffers(n: int, buffers: Sequence[int]) -> None: ...
def glGenVertexArrays(n: int) -> int: ...
def glBindVertexArray(array: int) -> None: ...
def glDeleteVertexArrays(n: int, arrays: Sequence[int]) -> None: ...
def glEnableVertexAttribArray(index: int) -> None: ...
def glVertexAttribPointer(
    index: int,
    size: int,
    type: int,
    normalized: bool | int,
    stride: int,
    pointer: Any,
) -> None: ...

# --- Texture functions ---

def glGenTextures(n: int) -> int: ...
def glBindTexture(target: int, texture: int) -> None: ...
def glDeleteTextures(textures: Sequence[int]) -> None: ...
def glPixelStorei(pname: int, param: int) -> None: ...
def glTexParameteri(target: int, pname: int, param: int) -> None: ...
def glTexImage2D(
    target: int,
    level: int,
    internalformat: int,
    width: int,
    height: int,
    border: int,
    format: int,
    type: int,
    pixels: Any,
) -> None: ...
def glActiveTexture(texture: int) -> None: ...

# --- Queries / misc ---

def glGetString(name: int) -> bytes | None: ...

# --- Uniforms / drawing / state ---

def glViewport(x: int, y: int, width: int, height: int) -> None: ...
def glDisable(cap: int) -> None: ...
def glEnable(cap: int) -> None: ...
def glClearColor(red: float, green: float, blue: float, alpha: float) -> None: ...
def glClear(mask: int) -> None: ...
def glUniform1i(location: int, v0: int) -> None: ...
def glUniform1f(location: int, v0: float) -> None: ...
def glUniform2f(location: int, v0: float, v1: float) -> None: ...
def glUniform4f(location: int, v0: float, v1: float, v2: float, v3: float) -> None: ...
def glDrawArrays(mode: int, first: int, count: int) -> None: ...
def glBlendFunc(sfactor: int, dfactor: int) -> None: ...
